# Generated by Django 6.1.1 on 2026-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='cover_url',
            field=models.CharField(max_length=255),
        ),
    ]
