# Generated by Django 6.1.1 on 2026-09-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_portfolioproject_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='sample_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(choices=[('starter', 'Under ₹25,000'), ('growth', '₹25,000 - ₹75,000'), ('business', '₹75,000 - ₹2,00,000'), ('enterprise', '₹2,00,000+'), ('unsure', 'Not sure yet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='timeline',
            field=models.CharField(choices=[('asap', 'As soon as possible'), ('1month', 'Within a month'), ('3months', '1-3 months'), ('flexible', 'Flexible')], max_length=20),
        ),
    ]
