# Generated by Django 6.0.4 on 2026-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_portfolioproject_sample_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in INR. Leave blank if not purchasable online.', max_digits=10, null=True),
        ),
    ]
